//====================================================================================================
// Code generated with Momentum: DAC Gen (Build 2.5.4750.27570)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by fmuraya at SOFTBOOKSSERVER on 08/24/2013 16:52:15 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Data;
using System.Data.Common;
using Microsoft.Practices.EnterpriseLibrary.Data;
using fanikiwaGL.Entities;

namespace fanikiwaGL.Data
{
    /// <summary>
    /// AccountTypes data access component. Manages CRUD operations for the AccountTypes table.
    /// </summary>
    public partial class AccountTypeDAC : DataAccessComponent
    {

        /// <summary>
        /// Inserts a new row in the AccountTypes table.
        /// </summary>
        /// <param name="accountType">A AccountType object.</param>
        /// <returns>An updated AccountType object.</returns>
        public AccountType Create(AccountType accountType)
        {
            const string SQL_STATEMENT =
                "INSERT INTO dbo.AccountTypes ([ShortCode], [Description]) " +
                "VALUES(@ShortCode, @Description); SELECT SCOPE_IDENTITY();";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@ShortCode", DbType.StringFixedLength, accountType.ShortCode);
                db.AddInParameter(cmd, "@Description", DbType.String, accountType.Description);

                // Get the primary key value.
                accountType.Id = Convert.ToInt32(db.ExecuteScalar(cmd));
            }

            return accountType;
        }

        /// <summary>
        /// Updates an existing row in the AccountTypes table.
        /// </summary>
        /// <param name="accountType">A AccountType entity object.</param>
        public void UpdateById(AccountType accountType)
        {
            const string SQL_STATEMENT =
                "UPDATE dbo.AccountTypes " +
                "SET " +
                    "[ShortCode]=@ShortCode, " +
                    "[Description]=@Description " +
                "WHERE [Id]=@Id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@ShortCode", DbType.StringFixedLength, accountType.ShortCode);
                db.AddInParameter(cmd, "@Description", DbType.String, accountType.Description);
                db.AddInParameter(cmd, "@Id", DbType.Int32, accountType.Id);

                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Conditionally deletes one or more rows in the AccountTypes table.
        /// </summary>
        /// <param name="id">A id value.</param>
        public void DeleteById(int id)
        {
            const string SQL_STATEMENT = "DELETE dbo.AccountTypes " +
                                         "WHERE [Id]=@Id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.

                db.AddInParameter(cmd, "@Id", DbType.Int32, id);


                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Returns a row from the AccountTypes table.
        /// </summary>
        /// <param name="id">A Id value.</param>
        /// <returns>A AccountType object with data populated from the database.</returns>
        public AccountType SelectById(int id)
        {
            const string SQL_STATEMENT =
                "SELECT [Id], [ShortCode], [Description] " +
                "FROM dbo.AccountTypes  " +
                "WHERE [Id]=@Id ";

            AccountType accountType = null;

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                db.AddInParameter(cmd, "@Id", DbType.Int32, id);

                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    if (dr.Read())
                    {
                        // Create a new AccountType
                        accountType = new AccountType();

                        // Read values.
                        accountType.Id = base.GetDataValue<int>(dr, "Id");
                        accountType.ShortCode = base.GetDataValue<string>(dr, "ShortCode");
                        accountType.Description = base.GetDataValue<string>(dr, "Description");
                    }
                }
            }

            return accountType;
        }

        /// <summary>
        /// Conditionally retrieves one or more rows from the AccountTypes table.
        /// </summary>
        /// <returns>A collection of AccountType objects.</returns>		
        public List<AccountType> Select()
        {
            // WARNING! The following SQL query does not contain a WHERE condition.
            // You are advised to include a WHERE condition to prevent any performance
            // issues when querying large resultsets.
            const string SQL_STATEMENT =
                "SELECT [Id], [ShortCode], [Description] " +
                "FROM dbo.AccountTypes ";

            List<AccountType> result = new List<AccountType>();

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    while (dr.Read())
                    {
                        // Create a new AccountType
                        AccountType accountType = new AccountType();

                        // Read values.
                        accountType.Id = base.GetDataValue<int>(dr, "Id");
                        accountType.ShortCode = base.GetDataValue<string>(dr, "ShortCode");
                        accountType.Description = base.GetDataValue<string>(dr, "Description");

                        // Add to List.
                        result.Add(accountType);
                    }
                }
            }

            return result;
        }
    }
}
