//====================================================================================================
// Code generated with Momentum: DAC Gen (Build 2.5.4750.27570)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by fmuraya at SOFTBOOKSSERVER on 09/26/2013 15:47:20 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Data;
using System.Data.Common;
using Microsoft.Practices.EnterpriseLibrary.Data;
using fanikiwaGL.Entities;

namespace fanikiwaGL.Data
{
    /// <summary>
    /// Customers data access component. Manages CRUD operations for the Customers table.
    /// </summary>
    public partial class CustomerDAC : DataAccessComponent
    {

        /// <summary>
        /// Conditionally deletes one or more rows in the Customers table.
        /// </summary>
        /// <param name="customerId">A customerId value.</param>
        public void DeleteById(int customerId)
        {
            const string SQL_STATEMENT = "DELETE dbo.Customers " +
                                         "WHERE [CustomerId]=@CustomerId ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.

                db.AddInParameter(cmd, "@CustomerId", DbType.Int32, customerId);


                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Inserts a new row in the Customers table.
        /// </summary>
        /// <param name="customer">A Customer object.</param>
        /// <returns>An updated Customer object.</returns>
        public Customer Create(Customer customer)
        {
            const string SQL_STATEMENT =
                "INSERT INTO dbo.Customers ([CustomerNo], [Name], [Address], [Telephone], [Email], [Branch], [BillToName], [BillToAddress], [BillToTelephone], [BillToEmail], [MemberId], [CreatedDate]) " +
                "VALUES(@CustomerNo, @Name, @Address, @Telephone, @Email, @Branch, @BillToName, @BillToAddress, @BillToTelephone, @BillToEmail, @MemberId, @CreatedDate); SELECT SCOPE_IDENTITY();";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@CustomerNo", DbType.String, customer.CustomerNo);
                db.AddInParameter(cmd, "@Name", DbType.String, customer.Name);
                db.AddInParameter(cmd, "@Address", DbType.String, customer.Address);
                db.AddInParameter(cmd, "@Telephone", DbType.String, customer.Telephone);
                db.AddInParameter(cmd, "@Email", DbType.String, customer.Email);
                db.AddInParameter(cmd, "@Branch", DbType.String, customer.Branch);
                db.AddInParameter(cmd, "@BillToName", DbType.String, customer.BillToName);
                db.AddInParameter(cmd, "@BillToAddress", DbType.String, customer.BillToAddress);
                db.AddInParameter(cmd, "@BillToTelephone", DbType.String, customer.BillToTelephone);
                db.AddInParameter(cmd, "@BillToEmail", DbType.String, customer.BillToEmail);
                db.AddInParameter(cmd, "@MemberId", DbType.Int32, customer.MemberId);
                db.AddInParameter(cmd, "@CreatedDate", DbType.Date, customer.CreatedDate);

                // Get the primary key value.
                customer.CustomerId = Convert.ToInt32(db.ExecuteScalar(cmd));
            }

            return customer;
        }

        /// <summary>
        /// Updates an existing row in the Customers table.
        /// </summary>
        /// <param name="customer">A Customer entity object.</param>
        public void UpdateById(Customer customer)
        {
            const string SQL_STATEMENT =
                "UPDATE dbo.Customers " +
                "SET " +
                    "[CustomerNo]=@CustomerNo, " +
                    "[Name]=@Name, " +
                    "[Address]=@Address, " +
                    "[Telephone]=@Telephone, " +
                    "[Email]=@Email, " +
                    "[Branch]=@Branch, " +
                    "[BillToName]=@BillToName, " +
                    "[BillToAddress]=@BillToAddress, " +
                    "[BillToTelephone]=@BillToTelephone, " +
                    "[BillToEmail]=@BillToEmail, " +
                    "[MemberId]=@MemberId, " +
                    "[CreatedDate]=@CreatedDate " +
                "WHERE [CustomerId]=@CustomerId ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@CustomerNo", DbType.String, customer.CustomerNo);
                db.AddInParameter(cmd, "@Name", DbType.String, customer.Name);
                db.AddInParameter(cmd, "@Address", DbType.String, customer.Address);
                db.AddInParameter(cmd, "@Telephone", DbType.String, customer.Telephone);
                db.AddInParameter(cmd, "@Email", DbType.String, customer.Email);
                db.AddInParameter(cmd, "@Branch", DbType.String, customer.Branch);
                db.AddInParameter(cmd, "@BillToName", DbType.String, customer.BillToName);
                db.AddInParameter(cmd, "@BillToAddress", DbType.String, customer.BillToAddress);
                db.AddInParameter(cmd, "@BillToTelephone", DbType.String, customer.BillToTelephone);
                db.AddInParameter(cmd, "@BillToEmail", DbType.String, customer.BillToEmail);
                db.AddInParameter(cmd, "@MemberId", DbType.Int32, customer.MemberId);
                db.AddInParameter(cmd, "@CreatedDate", DbType.Date, customer.CreatedDate);
                db.AddInParameter(cmd, "@CustomerId", DbType.Int32, customer.CustomerId);

                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Returns a row from the Customers table.
        /// </summary>
        /// <param name="customerId">A CustomerId value.</param>
        /// <returns>A Customer object with data populated from the database.</returns>
        public Customer SelectById(int customerId)
        {
            const string SQL_STATEMENT =
                "SELECT [CustomerId], [CustomerNo], [Name], [Address], [Telephone], [Email], [Branch], [BillToName]" +
                        ", [BillToAddress], [BillToTelephone], [BillToEmail], [MemberId], [CreatedDate] " +
                "FROM dbo.Customers  " +
                "WHERE [CustomerId]=@CustomerId ";

            Customer customer = null;

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                db.AddInParameter(cmd, "@CustomerId", DbType.Int32, customerId);

                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    if (dr.Read())
                    {
                        // Create a new Customer
                        customer = new Customer();

                        // Read values.
                        customer.CustomerId = base.GetDataValue<int>(dr, "CustomerId");
                        customer.CustomerNo = base.GetDataValue<string>(dr, "CustomerNo");
                        customer.Name = base.GetDataValue<string>(dr, "Name");
                        customer.Address = base.GetDataValue<string>(dr, "Address");
                        customer.Telephone = base.GetDataValue<string>(dr, "Telephone");
                        customer.Email = base.GetDataValue<string>(dr, "Email");
                        customer.Branch = base.GetDataValue<string>(dr, "Branch");
                        customer.BillToName = base.GetDataValue<string>(dr, "BillToName");
                        customer.BillToAddress = base.GetDataValue<string>(dr, "BillToAddress");
                        customer.BillToTelephone = base.GetDataValue<string>(dr, "BillToTelephone");
                        customer.BillToEmail = base.GetDataValue<string>(dr, "BillToEmail");
                        customer.MemberId = base.GetDataValue<int>(dr, "MemberId");
                        customer.CreatedDate = base.GetDataValue<DateTime>(dr, "CreatedDate");
                    }
                }
            }

            return customer;
        }

        /// <summary>
        /// Conditionally retrieves one or more rows from the Customers table.
        /// </summary>
        /// <returns>A collection of Customer objects.</returns>		
        public List<Customer> Select()
        {
            // WARNING! The following SQL query does not contain a WHERE condition.
            // You are advised to include a WHERE condition to prevent any performance
            // issues when querying large resultsets.
            const string SQL_STATEMENT =
                "SELECT [CustomerId], [CustomerNo], [Name], [Address], [Telephone], [Email], [Branch], [BillToName]" +
                        ", [BillToAddress], [BillToTelephone], [BillToEmail], [MemberId], [CreatedDate]  " +
                "FROM dbo.Customers ";

            List<Customer> result = new List<Customer>();

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    while (dr.Read())
                    {
                        // Create a new Customer
                        Customer customer = new Customer();

                        // Read values.
                        customer.CustomerId = base.GetDataValue<int>(dr, "CustomerId");
                        customer.CustomerNo = base.GetDataValue<string>(dr, "CustomerNo");
                        customer.Name = base.GetDataValue<string>(dr, "Name");
                        customer.Address = base.GetDataValue<string>(dr, "Address");
                        customer.Telephone = base.GetDataValue<string>(dr, "Telephone");
                        customer.Email = base.GetDataValue<string>(dr, "Email");
                        customer.Branch = base.GetDataValue<string>(dr, "Branch");
                        customer.BillToName = base.GetDataValue<string>(dr, "BillToName");
                        customer.BillToAddress = base.GetDataValue<string>(dr, "BillToAddress");
                        customer.BillToTelephone = base.GetDataValue<string>(dr, "BillToTelephone");
                        customer.BillToEmail = base.GetDataValue<string>(dr, "BillToEmail");
                        customer.CreatedDate = base.GetDataValue<DateTime>(dr, "CreatedDate");
                        customer.MemberId = base.GetDataValue<int>(dr, "MemberId");

                        // Add to List.
                        result.Add(customer);
                    }
                }
            }

            return result;
        }



        /// <summary>
        /// Returns a row from the Customers table.
        /// </summary>
        /// <param name="customerId">A CustomerId value.</param>
        /// <returns>A Customer object with data populated from the database.</returns>
        public Customer SelectByMember(int memberId)
        {
            const string SQL_STATEMENT =
                "SELECT [CustomerId], [CustomerNo], [Name], [Address], [Telephone], [Email], [Branch], [BillToName]" +
                        ", [BillToAddress], [BillToTelephone], [BillToEmail], [MemberId], [CreatedDate] " +
                "FROM dbo.Customers  " +
                "WHERE [MemberId]=@MemberId ";

            Customer customer = null;

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                db.AddInParameter(cmd, "@MemberId", DbType.Int32, memberId);

                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    if (dr.Read())
                    {
                        // Create a new Customer
                        customer = new Customer();

                        // Read values.
                        customer.CustomerId = base.GetDataValue<int>(dr, "CustomerId");
                        customer.CustomerNo = base.GetDataValue<string>(dr, "CustomerNo");
                        customer.Name = base.GetDataValue<string>(dr, "Name");
                        customer.Address = base.GetDataValue<string>(dr, "Address");
                        customer.Telephone = base.GetDataValue<string>(dr, "Telephone");
                        customer.Email = base.GetDataValue<string>(dr, "Email");
                        customer.Branch = base.GetDataValue<string>(dr, "Branch");
                        customer.BillToName = base.GetDataValue<string>(dr, "BillToName");
                        customer.BillToAddress = base.GetDataValue<string>(dr, "BillToAddress");
                        customer.BillToTelephone = base.GetDataValue<string>(dr, "BillToTelephone");
                        customer.BillToEmail = base.GetDataValue<string>(dr, "BillToEmail");
                        customer.MemberId = base.GetDataValue<int>(dr, "MemberId");
                        customer.CreatedDate = base.GetDataValue<DateTime>(dr, "CreatedDate");
                    }
                }
            }

            return customer;
        }


    }
}