//====================================================================================================
// Code generated with Velocity: SL Gen (Build 2.4.4750.27570)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by fmuraya at SOFTBOOKSSERVER on 10/21/2013 13:27:40 
//====================================================================================================

using System.Runtime.Serialization;

namespace fanikiwaGL.Services.Contracts
{
    /// <summary>
    /// Fault contract class.
    /// </summary>
    [DataContract]
    public class FinancialPostingFault
    {
        [DataMember]
        public string Message { get; set; }

        public FinancialPostingFault(string message)
        {
            this.Message = message;
        }
    }

    [DataContract]

    public class CustomExpMsg
    {

        public CustomExpMsg()
        {
            this.ErrorMsg = "Service encountered an error";
        }

        public CustomExpMsg(string message)
        {
            this.ErrorMsg = message;
        }

        private int errorNumber;

        [DataMember(Order = 0)]
        public int ErrorNumber
        {
            get { return errorNumber; }
            set { errorNumber = value; }
        }

        private string errrorMsg;

        [DataMember(Order = 1)]
        public string ErrorMsg
        {
            get { return errrorMsg; }
            set { errrorMsg = value; }
        }

        private string description;
        [DataMember(Order = 2)]
        public string Description
        {
            get { return description; }
            set { description = value; }
        }

    }

}