//====================================================================================================
// Code generated with Inertia: BE Gen (Build 2.5.4750.27569)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by francis.muraya at KPC7070W on 09/05/2013 18:49:45 
//====================================================================================================
 
using System; 
using System.Collections.Generic;
using System.Collections.ObjectModel; 
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Globalization;
using System.Linq; 
using System.Runtime.Serialization;

namespace fanikiwaGL.Entities
{
    /// <summary>
    /// Represents a row of Account data.
    /// </summary>
    [DataContract]
    public partial class Account
    {

        /// <summary>
        /// Gets or sets a int value for the AccountID column.
        /// </summary>
        [DataMember]
        [Display(Name = "Id")]
        public int AccountID { get; set; }

        /// <summary>
        /// Gets or sets a int value for the CustomerId column.
        /// </summary>
        [DataMember]
        [Display(Name = "Customer")]
        public int CustomerId { get; set; }

        /// <summary>
        /// Gets or sets a string value for the AccountName column.
        /// </summary>
        [DataMember]
        [Display(Name = "Account Name")]
        public string AccountName { get; set; }

        /// <summary>
        /// Gets or sets a string value for the AccountNo column.
        /// </summary>
        [DataMember]
        [Display(Name = "Account No")]
        public string AccountNo { get; set; }

        /// <summary>
        /// Gets or sets a int value for the AccountTypeId column.
        /// </summary>
        [DataMember]
        [Display(Name = "Account Type")]
        public int AccountTypeId { get; set; }

        /// <summary>
        /// Gets or sets a int value for the COAId column.
        /// </summary>
        [DataMember]
        [Display(Name = "COA")]
        public int COAId { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Branch column.
        /// </summary>
        [DataMember]
        [Display(Name = "Branch")]
        public string Branch { get; set; }

        /// <summary>
        /// Gets or sets a short value for the PassFlag column.
        /// </summary>
        [DataMember]
        [Display(Name = "Pass Flag")]
        public short PassFlag { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the BookBalance column.
        /// </summary>
        [DataMember]
        [Display(Name = "Book Balance")]
        public decimal BookBalance { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the ClearedBalance column.
        /// </summary>
        [DataMember]
        [Display(Name = "Cleared Balance")]
        public decimal ClearedBalance { get; set; }

        /// <summary>
        /// Gets or sets a double value for the InterestRate column.
        /// </summary>
        [DataMember]
        [Display(Name = "Interest Rate")]
        public double InterestRate { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the AccruedInt column.
        /// </summary>
        [DataMember]
        [Display(Name = "Accrued Interest")]
        public decimal AccruedInt { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the Limit column.
        /// </summary>
        [DataMember]
        [Display(Name = "Limit")]
        public decimal Limit { get; set; }

        /// <summary>
        /// Gets or sets a short value for the LimitFlag column.
        /// </summary>
        [DataMember]
        [Display(Name = "Limit Flag")]
        public short LimitFlag { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the Bal30 column.
        /// </summary>
        [DataMember]
        public decimal Bal30 { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the Bal60 column.
        /// </summary>
        [DataMember]
        public decimal Bal60 { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the Bal90 column.
        /// </summary>
        [DataMember]
        public decimal Bal90 { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the BalOver90 column.
        /// </summary>
        [DataMember]
        public decimal BalOver90 { get; set; }

        /// <summary>
        /// Gets or sets a double value for the IntRate30 column.
        /// </summary>
        [DataMember]
        public double IntRate30 { get; set; }

        /// <summary>
        /// Gets or sets a double value for the IntRate60 column.
        /// </summary>
        [DataMember]
        public double IntRate60 { get; set; }

        /// <summary>
        /// Gets or sets a double value for the IntRate90 column.
        /// </summary>
        [DataMember]
        public double IntRate90 { get; set; }

        /// <summary>
        /// Gets or sets a double value for the IntRateOver90 column.
        /// </summary>
        [DataMember]
        public double IntRateOver90 { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the Closed column.
        /// </summary>
        [DataMember]
        [Display(Name = "Closed")]
        public bool Closed { get; set; }

        /// <summary>
        /// Gets or sets a short value for the LimitCheckFlag column.
        /// </summary>
        [DataMember]
        [Display(Name = "Limit Check Flag")]
        public short LimitCheckFlag { get; set; }
    }
}
