//====================================================================================================
// Code generated with Inertia: BE Gen (Build 2.5.4750.27569)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by fmuraya at SOFTBOOKSSERVER on 08/24/2013 16:50:55 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace fanikiwaGL.Entities
{
    /// <summary>
    /// Represents a row of Customer data.
    /// </summary>
    [DataContract]
    public partial class Customer
    {

        /// <summary>
        /// Gets or sets a int value for the CustomerId column.
        /// </summary>
        [DataMember] 
        public int CustomerId { get; set; }

        /// <summary>
        /// Gets or sets a string value for the CustomerNo column.
        /// </summary>
        [DataMember]
        public string CustomerNo { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Name column.
        /// </summary>
        [DataMember]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Address column.
        /// </summary>
        [DataMember]
        public string Address { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Telephone column.
        /// </summary>
        [DataMember]
        public string Telephone { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Email column.
        /// </summary>
        [DataMember]
        public string Email { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Branch column.
        /// </summary>
        [DataMember]
        public string Branch { get; set; }

        /// <summary>
        /// Gets or sets a string value for the BillToName column.
        /// </summary>
        [DataMember]
        public string BillToName { get; set; }

        /// <summary>
        /// Gets or sets a string value for the BillToAddress column.
        /// </summary>
        [DataMember]
        public string BillToAddress { get; set; }

        /// <summary>
        /// Gets or sets a string value for the BillToTelephone column.
        /// </summary>
        [DataMember]
        public string BillToTelephone { get; set; }

        /// <summary>
        /// Gets or sets a string value for the BillToEmail column.
        /// </summary>
        [DataMember]
        public string BillToEmail { get; set; }

        /// <summary>
        /// Gets or sets a int value for the MemberId column.
        /// </summary>
        [DataMember]
        public int MemberId { get; set; }

        /// <summary>
        /// Gets or sets a int value for the CreatedDate column.
        /// </summary>
        [DataMember]
        public DateTime CreatedDate { get; set; }




    }
}
