//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 01/07/2015 18:32:54 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace fanikiwaGL.Entities
{
    /// <summary>
    /// Represents a row of DiaryProgramControl data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class DiaryProgramControl
    {
        /// <summary>
        /// Gets or sets a int value for the Id column.
        /// </summary>
        [DataMember]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the LastRun column.
        /// </summary>
        [DataMember]
        public DateTime LastRun { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the NextRun column.
        /// </summary>
        [DataMember]
        public DateTime NextRun { get; set; }
    }
}
