//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 01/09/2015 19:08:44 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace fanikiwaGL.Entities
{
    /// <summary>
    /// Represents a row of STO data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class STO
    {
        /// <summary>
        /// Gets or sets a int value for the Id column.
        /// </summary>
        [DataMember]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the AmountPaid column.
        /// </summary>
        [DataMember]
        public decimal AmountPaid { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the PayAmount column.
        /// </summary>
        [DataMember]
        public decimal PayAmount { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the TotalToPay column.
        /// </summary>
        [DataMember]
        public decimal TotalToPay { get; set; }

        /// <summary>
        /// Gets or sets a int value for the DrAccount column.
        /// </summary>
        [DataMember]
        public int DrAccount { get; set; }

        /// <summary>
        /// Gets or sets a int value for the CrAccount column.
        /// </summary>
        [DataMember]
        public int CrAccount { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the NextPayDate column.
        /// </summary>
        [DataMember]
        public DateTime NextPayDate { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the CreateDate column.
        /// </summary>
        [DataMember]
        public DateTime CreateDate { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the StartDate column.
        /// </summary>
        [DataMember]
        public DateTime StartDate { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Interval column.
        /// </summary>
        [DataMember]
        public string Interval { get; set; }

        /// <summary>
        /// Gets or sets a int value for the NoOfPayments column.
        /// </summary>
        [DataMember]
        public int NoOfPayments { get; set; }

        /// <summary>
        /// Gets or sets a int value for the NoOfPaymentsMade column.
        /// </summary>
        [DataMember]
        public int NoOfPaymentsMade { get; set; }

        /// <summary>
        /// Gets or sets a int value for the NoOfDefaults column.
        /// </summary>
        [DataMember]
        public int NoOfDefaults { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the AmountDefaulted column.
        /// </summary>
        [DataMember]
        public decimal AmountDefaulted { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the EndDate column.
        /// </summary>
        [DataMember]
        public DateTime EndDate { get; set; }

        /// <summary>
        /// Gets or sets a int value for the STOType column.
        /// </summary>
        [DataMember]
        public int STOType { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the ChargeCommFlag column.
        /// </summary>
        [DataMember]
        public bool ChargeCommFlag { get; set; }

        /// <summary>
        /// Gets or sets a short value for the CommFreqFlag column.
        /// </summary>
        [DataMember]
        public short CommFreqFlag { get; set; }

        /// <summary>
        /// Gets or sets a short value for the CommSourceFlag column.
        /// </summary>
        [DataMember]
        public short CommSourceFlag { get; set; }

        /// <summary>
        /// Gets or sets a short value for the ChargeWho column.
        /// </summary>
        [DataMember]
        public short ChargeWho { get; set; }

        /// <summary>
        /// Gets or sets a int value for the CommissionAccount column.
        /// </summary>
        [DataMember]
        public int CommissionAccount { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the CommissionPaidFlag column.
        /// </summary>
        [DataMember]
        public bool CommissionPaidFlag { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the CommissionAmount column.
        /// </summary>
        [DataMember]
        public decimal CommissionAmount { get; set; }

        /// <summary>
        /// Gets or sets a int value for the DrTxnType column.
        /// </summary>
        [DataMember]
        public int DrTxnType { get; set; }

        /// <summary>
        /// Gets or sets a int value for the CrTxnType column.
        /// </summary>
        [DataMember]
        public int CrTxnType { get; set; }

        /// <summary>
        /// Gets or sets a int value for the LimitFlag column.
        /// </summary>
        [DataMember]
        public int LimitFlag { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the PartialPay column.
        /// </summary>
        [DataMember]
        public bool PartialPay { get; set; }

        /// <summary>
        /// Gets or sets a int value for the LoanId column.
        /// </summary>
        [DataMember]
        public int LoanId { get; set; }

        /// <summary>
        /// Gets or sets a int value for the STOAccType column.
        /// </summary>
        [DataMember]
        public int STOAccType { get; set; }
    }
}
