//====================================================================================================
// Code generated with Inertia: BE Gen (Build 2.5.4750.27569)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by francis.muraya at KPC7070W on 08/21/2013 07:54:00 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace fanikiwaGL.Entities
{
    [DataContract]
    public partial class TieredDet
    {

        /// <summary>
        /// Gets or sets a int value for the Id column.
        /// </summary>
        [DataMember] 
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets a int value for the TieredID column.
        /// </summary>
        [DataMember]
        public int TieredID { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the Min column.
        /// </summary>
        [DataMember]
        public decimal Min { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the Max column.
        /// </summary>
        [DataMember]
        public decimal Max { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the Rate column.
        /// </summary>
        [DataMember]
        public decimal Rate { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the Absolute column.
        /// </summary>
        [DataMember]
        public bool Absolute { get; set; }


    }
}
