//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/08/2014 18:44:23 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Globalization;
using System.Linq;
using System.Runtime.Serialization;


namespace fanikiwaGL.Entities
{
    /// <summary>
    /// Represents a row of TransactionType data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class TransactionType
    {
        /// <summary>
        /// Gets or sets a int value for the TransactionTypeID column.
        /// </summary>
        [DataMember]
        [Display(Name = "Id")]
        public int TransactionTypeID { get; set; }

        /// <summary>
        /// Gets or sets a string value for the DebitCredit column.
        /// </summary>
        [DataMember]
        [Display(Name = "Debit/Credit")]
        public string DebitCredit { get; set; }

        /// <summary>
        /// Gets or sets a string value for the ShortCode column.
        /// </summary>
        [DataMember]
        [Display(Name = "Short Code")]
        public string ShortCode { get; set; }

        /// <summary>
        /// Gets or sets a short value for the TxnClass column.
        /// </summary>
        [DataMember]
        [Display(Name = "Txn Class")]
        public short TxnClass { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Description column.
        /// </summary>
        [DataMember]
        [Display(Name = "Description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the DefaultAmount column.
        /// </summary>
        [DataMember]
        [Display(Name = "Default Amount")]
        public decimal DefaultAmount { get; set; }

        /// <summary>
        /// Gets or sets a string value for the AmountExpression column.
        /// </summary>
        [DataMember]
        [Display(Name = "Amount Expression")]
        public string AmountExpression { get; set; }

        /// <summary>
        /// Gets or sets a int value for the DefaultMainAccount column.
        /// </summary>
        [DataMember]
        [Display(Name = "Default Main Account")]
        public int DefaultMainAccount { get; set; }

        /// <summary>
        /// Gets or sets a int value for the DefaultContraAccount column.
        /// </summary>
        [DataMember]
        [Display(Name = "Default Contra Account")]
        public int DefaultContraAccount { get; set; }

        /// <summary>
        /// Gets or sets a short value for the NarrativeFlag column.
        /// </summary>
        [DataMember]
        [Display(Name = "Narrative Flag")]
        public short NarrativeFlag { get; set; }

        /// <summary>
        /// Gets or sets a string value for the DefaultMainNarrative column.
        /// </summary>
        [DataMember]
        [Display(Name = "Default Main Narrative")]
        public string DefaultMainNarrative { get; set; }

        /// <summary>
        /// Gets or sets a string value for the DefaultContraNarrative column.
        /// </summary>
        [DataMember]
        [Display(Name = "Default Contra Narrative")]
        public string DefaultContraNarrative { get; set; }

        /// <summary>
        /// Gets or sets a short value for the TxnTypeView column.
        /// </summary>
        [DataMember]
        [Display(Name = "Txn Type View")]
        public short TxnTypeView { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the ChargeCommission column.
        /// </summary>
        [DataMember]
        [Display(Name = "Charge Commission")]
        public bool ChargeCommission { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the ChargeCommissionToTransaction column.
        /// </summary>
        [DataMember]
        [Display(Name = "Charge Commission To Transaction")]
        public bool ChargeCommissionToTransaction { get; set; }

        /// <summary>
        /// Gets or sets a string value for the CommissionAmountExpression column.
        /// </summary>
        [DataMember]
        [Display(Name = "Commission Amount Expression")]
        public string CommissionAmountExpression { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the CommissionDrAnotherAccount column.
        /// </summary>
        [DataMember]
        [Display(Name = "Commission Dr Another Account")]
        public bool CommissionDrAnotherAccount { get; set; }

        /// <summary>
        /// Gets or sets a int value for the CommissionDrAccount column.
        /// </summary>
        [DataMember]
        [Display(Name = "Commission Dr Account")]
        public int CommissionDrAccount { get; set; }

        /// <summary>
        /// Gets or sets a int value for the CommissionCrAccount column.
        /// </summary>
        [DataMember]
        [Display(Name = "Commission Cr Account")]
        public int CommissionCrAccount { get; set; }

        /// <summary>
        /// Gets or sets a short value for the CommissionNarrativeFlag column.
        /// </summary>
        [DataMember]
        [Display(Name = "Commission Narrative Flag")]
        public short CommissionNarrativeFlag { get; set; }

        /// <summary>
        /// Gets or sets a string value for the CommissionMainNarrative column.
        /// </summary>
        [DataMember]
        [Display(Name = "Commission Main Narrative")]
        public string CommissionMainNarrative { get; set; }

        /// <summary>
        /// Gets or sets a string value for the CommissionContraNarrative column.
        /// </summary>
        [DataMember]
        [Display(Name = "Commission Contra Narrative")]
        public string CommissionContraNarrative { get; set; }

        /// <summary>
        /// Gets or sets a string value for the CommComputationMethod column.
        /// </summary>
        [DataMember]
        [Display(Name = "Comm Computation Method")]
        public string CommComputationMethod { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the Absolute column.
        /// </summary>
        [DataMember]
        [Display(Name = "Absolute")]
        public bool Absolute { get; set; }

        /// <summary>
        /// Gets or sets a int value for the TieredTableId column.
        /// </summary>
        [DataMember]
        [Display(Name = "Tiered Table")]
        public int TieredTableId { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the CommissionAmount column.
        /// </summary>
        [DataMember]
        [Display(Name = "Commission Amount")]
        public decimal CommissionAmount { get; set; }

        /// <summary>
        /// Gets or sets a short value for the DialogFlag column.
        /// </summary>
        [DataMember]
        [Display(Name = "Dialog Flag")]
        public short DialogFlag { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the ForcePost column.
        /// </summary>
        [DataMember]
        [Display(Name = "Force Post")]
        public bool ForcePost { get; set; }

        /// <summary>
        /// Gets or sets a string value for the StatFlag column.
        /// </summary>
        [DataMember]
        [Display(Name = "Stat Flag")]
        public string StatFlag { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Screen column.
        /// </summary>
        [DataMember]
        [Display(Name = "Screen")]
        public string Screen { get; set; }

        /// <summary>
        /// Gets or sets a short value for the ValueDateOffset column.
        /// </summary>
        [DataMember]
        [Display(Name = "Value Date Offset")]
        public short ValueDateOffset { get; set; }

        /// <summary>
        /// Gets or sets a string value for the ChargeWho column.
        /// </summary>
        [DataMember]
        [Display(Name = "Charge Who")]
        public string ChargeWho { get; set; }

        /// <summary>
        /// Gets or sets a string value for the DrCommCalcMethod column.
        /// </summary>
        [DataMember]
        [Display(Name = "Dr Comm Calc Method")]
        public string DrCommCalcMethod { get; set; }

        /// <summary>
        /// Gets or sets a string value for the CrCommCalcMethod column.
        /// </summary>
        [DataMember]
        [Display(Name = "Cr Comm Calc Method")]
        public string CrCommCalcMethod { get; set; }

        /// <summary>
        /// Gets or sets a int value for the CommissionTransactionType column.
        /// </summary>
        [DataMember]
        [Display(Name = "Commission Transaction Type")]
        public int CommissionTransactionType { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the CanSuspend column.
        /// </summary>
        [DataMember]
        [Display(Name = "Can Suspend")]
        public bool CanSuspend { get; set; }

        /// <summary>
        /// Gets or sets a int value for the SuspenseCrAccount column.
        /// </summary>
        [DataMember]
        [Display(Name = "Suspense Cr Account")]
        public int SuspenseCrAccount { get; set; }

        /// <summary>
        /// Gets or sets a int value for the SuspenseDrAccount column.
        /// </summary>
        [DataMember]
        [Display(Name = "Suspense Dr Account")]
        public int SuspenseDrAccount { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the PrintReceiptPrompt column.
        /// </summary>
        [DataMember]
        [Display(Name = "Print Receipt Prompt")]
        public bool PrintReceiptPrompt { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the PrintReceipt column.
        /// </summary>
        [DataMember]
        [Display(Name = "Print Receipt")]
        public bool PrintReceipt { get; set; }

        /// <summary>
        /// Gets or sets a string value for the ReceiptLayout column.
        /// </summary>
        [DataMember]
        [Display(Name = "Receipt Layout")]
        public string ReceiptLayout { get; set; }
    }
}
