//====================================================================================================
// Code generated with Inertia: BE Gen (Build 2.5.4750.27569)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by francis.muraya at KPC7070W on 08/21/2013 07:54:00 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace fanikiwaGL.Entities
{
    /// <summary>
    /// Represents a row of TransactionChainNode data.
    /// </summary>
    [DataContract]
    public partial class TransactionChainNode
    {

        /// <summary>
        /// Gets or sets a int value for the NodeId column.
        /// </summary>
        [DataMember] 
        public int NodeId { get; set; }

        /// <summary>
        /// Gets or sets a int value for the ParentId column.
        /// </summary>
        [DataMember]
        public int ParentId { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Descripion column.
        /// </summary>
        [DataMember]
        public string Descripion { get; set; }

        /// <summary>
        /// Gets or sets a int value for the TransactionType column.
        /// </summary>
        [DataMember]
        public int TransactionType { get; set; }
    }
}
