//====================================================================================================
// Code generated with Inertia: BE Gen (Build 2.5.4750.27569)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by fmuraya at SOFTBOOKSSERVER on 08/24/2013 16:50:55 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace fanikiwaGL.Entities
{
    /// <summary>
    /// Represents a row of Transaction data.
    /// </summary>
    [DataContract]
    public partial class Transaction
    {

        /// <summary>
        /// Gets or sets a int value for the TransactionID column.
        /// </summary>
        [DataMember] 
        public int TransactionID { get; set; }

        /// <summary>
        /// Gets or sets a int value for the TransactionTypeId column.
        /// </summary>
        [DataMember]
        public int TransactionTypeId { get; set; }

        /// <summary>
        /// Gets or sets a int value for the AccountID column.
        /// </summary>
        [DataMember]
        public int AccountID { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the Amount column.
        /// </summary>
        [DataMember]
        public decimal Amount { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the PostDate column.
        /// </summary>
        [DataMember]
        public DateTime PostDate { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the RecordDate column.
        /// </summary>
        [DataMember]
        public DateTime RecordDate { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the ValueDate column.
        /// </summary>
        [DataMember]
        public DateTime ValueDate { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Narrative column.
        /// </summary>
        [DataMember]
        public string Narrative { get; set; }

        /// <summary>
        /// Gets or sets a string value for the StatementFlag column.
        /// </summary>
        [DataMember]
        [Display(Name = "Statement Flag")]
        public string StatementFlag { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Authorizer column.
        /// </summary>
        [DataMember]
        public string Authorizer { get; set; }

        /// <summary>
        /// Gets or sets a string value for the UserID column.
        /// </summary>
        [DataMember]
        public string UserID { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the ForcePostFlag column.
        /// </summary>
        [DataMember]
        public bool ForcePostFlag { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Reference column.
        /// </summary>
        [DataMember]
        public string Reference { get; set; }

        /// <summary>
        /// Gets or sets a string value for the ContraReference column.
        /// </summary>
        [DataMember]
        public string ContraReference { get; set; }
    }
}
