
//====================================================================================================
// Code generated with Inertia: BE Gen (Build 2.5.4750.27569)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by fmuraya at SOFTBOOKSSERVER on 08/24/2013 16:50:55 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace fanikiwaGL.Entities
{
    /// <summary>
    /// Represents a row of Transaction data.
    /// </summary>
    [DataContract]
    public partial class TransactionModel
    {

        /// <summary>
        /// Gets or sets a int value for the TransactionID column.
        /// </summary>
        [DataMember] 
        public int TransactionID { get; set; }
        /// <summary>
        /// Gets or sets a DateTime value for the PostDate column.
        /// </summary>
        [DataMember]
        public DateTime PostDate { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Narrative column.
        /// </summary>
        [DataMember]
        public string Narrative { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the Amount column.
        /// </summary>
        [DataMember]
        public decimal Debit { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the Amount column.
        /// </summary>
        [DataMember]
        public decimal Credit { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the Amount column.
        /// </summary>
        [DataMember]
        public decimal Balance { get; set; }


        /// <summary>
        /// Gets or sets a decimal value for the Amount column.
        /// </summary>
        [DataMember]
        public decimal Amount { get; set; }

        // <summary>
        /// Gets or sets a string value for the Narrative column.
        /// </summary>
        [DataMember]
        public string ContraReference { get; set; }


        
    }
}
