//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by francis.muraya at KPC0201M on 11/10/2014 14:39:05 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace fanikiwaGL.Entities
{
    /// <summary>
    /// Represents a row of ValueDatedTransaction data.
    /// </summary>
    [DataContract]
    public partial class ValueDatedTransaction
    {
        /// <summary>
        /// Gets or sets a int value for the TransactionID column.
        /// </summary>
        [DataMember] 
        public int TransactionID { get; set; }

        /// <summary>
        /// Gets or sets a int value for the TransactionTypeId column.
        /// </summary>
        [DataMember]
        public int TransactionTypeId { get; set; }

        /// <summary>
        /// Gets or sets a int value for the AccountID column.
        /// </summary>
        [DataMember]
        public int AccountID { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the Amount column.
        /// </summary>
        [DataMember]
        public decimal Amount { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the PostDate column.
        /// </summary>
        [DataMember]
        public DateTime PostDate { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the RecordDate column.
        /// </summary>
        [DataMember]
        public DateTime RecordDate { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the ValueDate column.
        /// </summary>
        [DataMember]
        public DateTime ValueDate { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Narrative column.
        /// </summary>
        [DataMember]
        public string Narrative { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the ForcePostFlag column.
        /// </summary>
        [DataMember]
        public bool ForcePostFlag { get; set; }

        /// <summary>
        /// Gets or sets a string value for the StatementFlag column.
        /// </summary>
        [DataMember]
        public string StatementFlag { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Authorizer column.
        /// </summary>
        [DataMember]
        public string Authorizer { get; set; }

        /// <summary>
        /// Gets or sets a string value for the UserID column.
        /// </summary>
        [DataMember]
        public string UserID { get; set; }
    }
}
